[package]
name = "pupactor_macro"
version = "0.2.5"
edition = "2024"
description = "Macros for pupactor"
license = "MIT OR Apache-2.0"
repository = "https://github.com/incker/pupactor"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.47"
syn = {  version = "3.0.3", features = ["full"]}

[lints.rust]
unsafe_code = "forbid"
